package constants

const ADDING string = "Adding"
const ALL string = "all"
const AMENDING string = "Amending"
const APPLICATION_NAME = "Khronos"
const AT string = "at"
const BREAK string = "***break"
const CARBON_DATE_FORMAT string = "Y-m-d"
const CARBON_START_END_TIME_FORMAT string = "h:ia"
const CONFIGURATION_FILE string = ".khronos.yaml"
const DATABASE_FILE string = "database_file"
const DATE_FORMAT string = "2006-01-02" // WTF golang?  Why this date format?
const DATE_NORMAL_CASE = "Date"
const DATE_TIME_NORMAL_CASE = "Date Time"
const DURATION_NORMAL_CASE = "Duration"
const DRY_RUN = "dry-run"
const EMPTY string = ""
const FATAL_NORMAL_CASE string = "Fatal"
const FAVORITE string = "favorite"
const FAVORITES string = "favorites"
const HELLO string = "***hello"
const INDENT_AMOUNT int = 4
const NATURAL_LANGUAGE_DESCRIPTION string = "Natural Language Time, e.g., '18 minutes ago'"
const NOTE string = "note"
const NOTE_DESCRIPTION string = "A note associated with this entry"
const NOTE_NORMAL_CASE = "Note"
const PRINT_DATE_WIDTH int = 10
const PRINT_DURATION_WIDTH int = 38
const PRINT_NOTE_WIDTH int = 40
const PRINT_PROJECT_WIDTH int = 20
const PRINT_START_END_WIDTH int = 20
const PRINT_TASK_WIDTH int = 20
const PRIOR_YEARS string = "prior-years"
const PROJECT string = "project"
const PROJECT_NORMAL_CASE = "Project"
const PROJECTS_NORMAL_CASE = "Project(s)"
const REPORT_BY_DAY = "report.by_day"
const REPORT_BY_DAY_FORMAT string = "%-10s  %-38s  %-20s  %-20s"
const REPORT_BY_ENTRY = "report.by_entry"
const REPORT_BY_ENTRY_FORMAT string = "%-38s  %-10s  %-20s  %-20s  %-20s  %-40s"
const REPORT_BY_PROJECT = "report.by_project"
const REPORT_BY_PROJECT_FORMAT string = "%-38s  %-20s  %-20s"
const REPORT_BY_TASK = "report.by_task"
const REPORT_CARBON_TO_FROM_FORMAT string = "Y-M-d"
const ROUND_TO_MINUTES string = "round_to_minutes"
const SECONDS_PER_DAY = 86400
const SHOW_BY_DAY_TOTALS string = "show_by_day_totals"
const SPACE_CHARACTER string = " "
const SPLIT_WORK_FROM_BREAK_TIME string = "split_work_from_break_time"
const START_END_NORMAL_CASE = "Start-End"
const STATISTICS string = "statistics"
const TASK string = "task"
const TASK_DELIMITER string = "+"
const TASK_NORMAL_CASE = "Task"
const TASKS_NORMAL_CASE = "Task(s)"
const TOTAL = "TOTAL"
const UNKNOWN_UID int64 = -1
const URL = "url"
const URL_NORMAL_CASE = "URL"
const WEB_SITE string = "https://github.com/jlanzarotta/khronos/"
const WEEK_START string = "week_start"
